In [73]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import sklearn.tree as tree

In [74]:
df = pd.read_csv('drug200.csv')
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [75]:
df.shape

(200, 6)

In [76]:
X = df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [77]:
np.unique(X[:, 4])

array([6.269, 6.683, 6.769, 7.261, 7.285, 7.298, 7.34, 7.477, 7.49, 7.761,
       7.798, 7.845, 8.011, 8.107, 8.151, 8.37, 8.607, 8.621, 8.7, 8.75,
       8.966, 8.968, 9.084, 9.17, 9.281, 9.381, 9.443, 9.445, 9.475,
       9.514, 9.567, 9.664, 9.677, 9.709, 9.712, 9.849, 9.894, 9.945,
       10.017, 10.065, 10.067, 10.091, 10.103, 10.114, 10.189, 10.291,
       10.292, 10.403, 10.443, 10.444, 10.446, 10.537, 10.605, 10.832,
       10.84, 10.898, 10.977, 11.009, 11.014, 11.037, 11.198, 11.227,
       11.262, 11.326, 11.34, 11.343, 11.349, 11.424, 11.455, 11.567,
       11.686, 11.767, 11.871, 11.939, 11.953, 12.006, 12.26, 12.295,
       12.307, 12.495, 12.703, 12.766, 12.854, 12.856, 12.859, 12.879,
       12.894, 12.923, 13.091, 13.093, 13.127, 13.303, 13.313, 13.597,
       13.598, 13.769, 13.884, 13.934, 13.935, 13.938, 13.967, 13.972,
       14.02, 14.133, 14.16, 14.216, 14.239, 14.642, 15.015, 15.036,
       15.156, 15.171, 15.376, 15.436, 15.478, 15.49, 15.516, 15.79,
       15.

In [78]:
from sklearn import preprocessing

le_sex = preprocessing.LabelEncoder() # we need numerical values for machine to understand
le_sex.fit(['M', 'F']) #teaches what to fit
X[:, 1] = le_sex.transform(X[:, 1]) #fits as per requirement, here for all row(:) and second column(1)

le_bp = preprocessing.LabelEncoder()
le_bp.fit(['HIGH', 'LOW', 'NORMAL'])
X[:, 2] = le_bp.transform(X[:, 2])

le_cho = preprocessing.LabelEncoder()
le_cho.fit(['HIGH', 'NORMAL'])
X[:, 3] = le_cho.transform(X[:, 3])

# le_drg = preprocessing.LabelEncoder()
# le_drg.fit(['drugA', 'drugB', 'drugC', 'drugX', 'drugY'])
# X[:, 5] = le_drg.transform(X[:, 5])

X[:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [79]:
y = df['Drug']
y[:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

In [82]:
# dividing data into train/test split
# using capitalized 'X' to represent 2d array (matrix)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 3) 
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(140, 5) (60, 5)
(140,) (60,)
